# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrackerServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13TrackerServer.proto\x12\rTrackerServer\"\"\n\x0e\x41\x64\x64UserRequest\x12\x10\n\x08group_ip\x18\x01 \x01(\x05\"?\n\x0f\x41\x64\x64UserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"1\n\x12\x44\x65leteUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\">\n\x10\x41\x64\x64ServerRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"K\n\x11\x41\x64\x64ServerResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x19\n\x11storage_server_id\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t2\x82\x02\n\rTrackerServer\x12J\n\x07\x41\x64\x64User\x12\x1d.TrackerServer.AddUserRequest\x1a\x1e.TrackerServer.AddUserResponse\"\x00\x12S\n\nDeleteUser\x12 .TrackerServer.DeleteUserRequest\x1a!.TrackerServer.DeleteUserResponse\"\x00\x12P\n\tAddServer\x12\x1f.TrackerServer.AddServerRequest\x1a .TrackerServer.AddServerResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TrackerServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDUSERREQUEST._serialized_start=38
  _ADDUSERREQUEST._serialized_end=72
  _ADDUSERRESPONSE._serialized_start=74
  _ADDUSERRESPONSE._serialized_end=137
  _DELETEUSERREQUEST._serialized_start=139
  _DELETEUSERREQUEST._serialized_end=175
  _DELETEUSERRESPONSE._serialized_start=177
  _DELETEUSERRESPONSE._serialized_end=226
  _ADDSERVERREQUEST._serialized_start=228
  _ADDSERVERREQUEST._serialized_end=290
  _ADDSERVERRESPONSE._serialized_start=292
  _ADDSERVERRESPONSE._serialized_end=367
  _TRACKERSERVER._serialized_start=370
  _TRACKERSERVER._serialized_end=628
# @@protoc_insertion_point(module_scope)
