# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LockServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10LockServer.proto\"c\n\x0bLockRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x11\n\tlock_type\x18\x05 \x01(\t\"\x1f\n\x0cLockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"A\n\rUnlockRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\"!\n\x0eUnlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32`\n\nLockServer\x12%\n\x04Lock\x12\x0c.LockRequest\x1a\r.LockResponse\"\x00\x12+\n\x06Unlock\x12\x0e.UnlockRequest\x1a\x0f.UnlockResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LockServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCKREQUEST._serialized_start=20
  _LOCKREQUEST._serialized_end=119
  _LOCKRESPONSE._serialized_start=121
  _LOCKRESPONSE._serialized_end=152
  _UNLOCKREQUEST._serialized_start=154
  _UNLOCKREQUEST._serialized_end=219
  _UNLOCKRESPONSE._serialized_start=221
  _UNLOCKRESPONSE._serialized_end=254
  _LOCKSERVER._serialized_start=256
  _LOCKSERVER._serialized_end=352
# @@protoc_insertion_point(module_scope)
