# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LockServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10LockServer.proto\"\x1c\n\ntestReplay\x12\x0e\n\x06status\x18\x01 \x01(\t\"c\n\x0bLockRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x11\n\tlock_type\x18\x05 \x01(\x05\"\x1e\n\x0cLockResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"e\n\rUnlockRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x11\n\tlock_type\x18\x05 \x01(\x05\" \n\x0eUnlockResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"#\n\x0f\x41\x64\x64GroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x05\"\"\n\x10\x41\x64\x64GroupResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x88\x01\n\rAddACLRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x0f\n\x07is_read\x18\x05 \x01(\x08\x12\x10\n\x08is_write\x18\x06 \x01(\x08\x12\x11\n\tis_delete\x18\x07 \x01(\x08\" \n\x0e\x41\x64\x64\x41\x43LResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"B\n\x0e\x41\x64\x64\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\x05\"!\n\x0f\x41\x64\x64\x46ileResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xf0\x01\n\nLockServer\x12%\n\x04Lock\x12\x0c.LockRequest\x1a\r.LockResponse\"\x00\x12+\n\x06Unlock\x12\x0e.UnlockRequest\x1a\x0f.UnlockResponse\"\x00\x12\x31\n\x08\x41\x64\x64Group\x12\x10.AddGroupRequest\x1a\x11.AddGroupResponse\"\x00\x12+\n\x06\x41\x64\x64\x41\x43L\x12\x0e.AddACLRequest\x1a\x0f.AddACLResponse\"\x00\x12.\n\x07\x41\x64\x64\x46ile\x12\x0f.AddFileRequest\x1a\x10.AddFileResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LockServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTREPLAY._serialized_start=20
  _TESTREPLAY._serialized_end=48
  _LOCKREQUEST._serialized_start=50
  _LOCKREQUEST._serialized_end=149
  _LOCKRESPONSE._serialized_start=151
  _LOCKRESPONSE._serialized_end=181
  _UNLOCKREQUEST._serialized_start=183
  _UNLOCKREQUEST._serialized_end=284
  _UNLOCKRESPONSE._serialized_start=286
  _UNLOCKRESPONSE._serialized_end=318
  _ADDGROUPREQUEST._serialized_start=320
  _ADDGROUPREQUEST._serialized_end=355
  _ADDGROUPRESPONSE._serialized_start=357
  _ADDGROUPRESPONSE._serialized_end=391
  _ADDACLREQUEST._serialized_start=394
  _ADDACLREQUEST._serialized_end=530
  _ADDACLRESPONSE._serialized_start=532
  _ADDACLRESPONSE._serialized_end=564
  _ADDFILEREQUEST._serialized_start=566
  _ADDFILEREQUEST._serialized_end=632
  _ADDFILERESPONSE._serialized_start=634
  _ADDFILERESPONSE._serialized_end=667
  _LOCKSERVER._serialized_start=670
  _LOCKSERVER._serialized_end=910
# @@protoc_insertion_point(module_scope)
