# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import APIs.StorageServer_pb2 as StorageServer__pb2


class StorageServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/StorageServer/Create',
                request_serializer=StorageServer__pb2.CreateRequest.SerializeToString,
                response_deserializer=StorageServer__pb2.CreateResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/StorageServer/Delete',
                request_serializer=StorageServer__pb2.DeleteRequest.SerializeToString,
                response_deserializer=StorageServer__pb2.DeleteResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/StorageServer/Read',
                request_serializer=StorageServer__pb2.ReadRequest.SerializeToString,
                response_deserializer=StorageServer__pb2.ReadResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/StorageServer/Write',
                request_serializer=StorageServer__pb2.WriteRequest.SerializeToString,
                response_deserializer=StorageServer__pb2.WriteResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/StorageServer/List',
                request_serializer=StorageServer__pb2.ListRequest.SerializeToString,
                response_deserializer=StorageServer__pb2.ListResponse.FromString,
                )
        self.GetTime = channel.unary_unary(
                '/StorageServer/GetTime',
                request_serializer=StorageServer__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=StorageServer__pb2.GetTimeResponse.FromString,
                )


class StorageServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=StorageServer__pb2.CreateRequest.FromString,
                    response_serializer=StorageServer__pb2.CreateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=StorageServer__pb2.DeleteRequest.FromString,
                    response_serializer=StorageServer__pb2.DeleteResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=StorageServer__pb2.ReadRequest.FromString,
                    response_serializer=StorageServer__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=StorageServer__pb2.WriteRequest.FromString,
                    response_serializer=StorageServer__pb2.WriteResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=StorageServer__pb2.ListRequest.FromString,
                    response_serializer=StorageServer__pb2.ListResponse.SerializeToString,
            ),
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=StorageServer__pb2.GetTimeRequest.FromString,
                    response_serializer=StorageServer__pb2.GetTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StorageServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StorageServer/Create',
            StorageServer__pb2.CreateRequest.SerializeToString,
            StorageServer__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StorageServer/Delete',
            StorageServer__pb2.DeleteRequest.SerializeToString,
            StorageServer__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StorageServer/Read',
            StorageServer__pb2.ReadRequest.SerializeToString,
            StorageServer__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StorageServer/Write',
            StorageServer__pb2.WriteRequest.SerializeToString,
            StorageServer__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StorageServer/List',
            StorageServer__pb2.ListRequest.SerializeToString,
            StorageServer__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StorageServer/GetTime',
            StorageServer__pb2.GetTimeRequest.SerializeToString,
            StorageServer__pb2.GetTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
