# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StorageServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13StorageServer.proto\"@\n\rCreateRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"!\n\x0e\x43reateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\rDeleteRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x0bReadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"/\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"M\n\x0cWriteRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04mode\x18\x04 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x12GetFileListRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"k\n\x13GetFileListResponse\x12,\n\tfile_list\x18\x01 \x03(\x0b\x32\x19.GetFileListResponse.File\x1a&\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t2\xf6\x01\n\rStorageServer\x12+\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\"\x00\x12+\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\"\x00\x12%\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\"\x00\x12(\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\"\x00\x12:\n\x0bGetFileList\x12\x13.GetFileListRequest\x1a\x14.GetFileListResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StorageServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEREQUEST._serialized_start=23
  _CREATEREQUEST._serialized_end=87
  _CREATERESPONSE._serialized_start=89
  _CREATERESPONSE._serialized_end=122
  _DELETEREQUEST._serialized_start=124
  _DELETEREQUEST._serialized_end=171
  _DELETERESPONSE._serialized_start=173
  _DELETERESPONSE._serialized_end=206
  _READREQUEST._serialized_start=208
  _READREQUEST._serialized_end=253
  _READRESPONSE._serialized_start=255
  _READRESPONSE._serialized_end=302
  _WRITEREQUEST._serialized_start=304
  _WRITEREQUEST._serialized_end=381
  _WRITERESPONSE._serialized_start=383
  _WRITERESPONSE._serialized_end=415
  _GETFILELISTREQUEST._serialized_start=417
  _GETFILELISTREQUEST._serialized_end=451
  _GETFILELISTRESPONSE._serialized_start=453
  _GETFILELISTRESPONSE._serialized_end=560
  _GETFILELISTRESPONSE_FILE._serialized_start=522
  _GETFILELISTRESPONSE_FILE._serialized_end=560
  _STORAGESERVER._serialized_start=563
  _STORAGESERVER._serialized_end=809
# @@protoc_insertion_point(module_scope)
