# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\r\n\x0bTestRequest\"\x1e\n\x0cTestResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x44\n\x0bTestService\x12\x35\n\nTestMethod\x12\x11.test.TestRequest\x1a\x12.test.TestResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTREQUEST._serialized_start=20
  _TESTREQUEST._serialized_end=33
  _TESTRESPONSE._serialized_start=35
  _TESTRESPONSE._serialized_end=65
  _TESTSERVICE._serialized_start=67
  _TESTSERVICE._serialized_end=135
# @@protoc_insertion_point(module_scope)
